apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: spe-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: meenal933/caption:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
