apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: image-caption-ingress
  namespace: spe-project
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"

spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:

      # 🔹 Frontend (UI)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80

      # 🔹 Caption API
      - path: /api/caption
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80

      # 🔹 Object Detection API (FIXED)
      - path: /api/detect
        pathType: Prefix
        backend:
          service:
            name: object-detector-service
            port:
              number: 80
