apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-deployment
  namespace: spe-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object
  template:
    metadata:
      labels:
        app: object
    spec:
      containers:
      - name: object
        image: meenal933/object:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: object-service
  namespace: spe-project
spec:
  selector:
    app: object
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
